services:
  agent:
    build: .
    environment:
      - APP_ENV
      - MAIN_SERVER_URL
      - AGENT_API_KEY
      - HTTP_PORT=8080
      - LOG_LEVEL
      - LOG_OUTPUT
      - PRINTER_IP
      - DESI_PRINTER_IP
      - PIZZA_PRINTER_IP
      - SUB_PRINTER_IP
      - WINGS_PRINTER_IP
      - PRINTER_DETECT_DELAY
      - PUSHOVER_APP_TOKEN
      - PUSHOVER_USER_KEY
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_SERVICE_NAME
    restart: unless-stopped
    networks:
      - agent-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - agent
    restart: unless-stopped
    networks:
      - agent-net

networks:
  agent-net:
    driver: bridge
