// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderState string

const (
	OrderStateArrived  OrderState = "arrived"
	OrderStateAccepted OrderState = "accepted"
)

func (e *OrderState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderState(s)
	case string:
		*e = OrderState(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderState: %T", src)
	}
	return nil
}

type NullOrderState struct {
	OrderState OrderState `json:"order_state"`
	Valid      bool       `json:"valid"` // Valid is true if OrderState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderState) Scan(value interface{}) error {
	if value == nil {
		ns.OrderState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderState), nil
}

type Order struct {
	OrderID     int32              `json:"order_id"`
	Payload     []byte             `json:"payload"`
	State       OrderState         `json:"state"`
	ArrivalDate pgtype.Timestamptz `json:"arrival_date"`
	PrintedDate pgtype.Timestamptz `json:"printed_date"`
}

type Setting struct {
	ID         int32              `json:"id"`
	AutoAccept bool               `json:"auto_accept"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
