// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOlderThan = `-- name: DeleteOlderThan :execrows
DELETE FROM orders
WHERE arrival_date < $1
`

func (q *Queries) DeleteOlderThan(ctx context.Context, arrivalDate pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOlderThan, arrivalDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAutoAccept = `-- name: GetAutoAccept :one
SELECT auto_accept FROM settings WHERE id = 1
`

func (q *Queries) GetAutoAccept(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getAutoAccept)
	var auto_accept bool
	err := row.Scan(&auto_accept)
	return auto_accept, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT order_id, payload, state, arrival_date, printed_date
FROM orders
WHERE order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.Payload,
		&i.State,
		&i.ArrivalDate,
		&i.PrintedDate,
	)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT order_id, payload, state, arrival_date, printed_date
FROM orders
WHERE order_id = $1
FOR UPDATE
`

// Row-level lock so the accept path is serialized against concurrent calls
// (e.g. mobile double-tap). Used inside the accept transaction.
func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, orderID int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUpdate, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.Payload,
		&i.State,
		&i.ArrivalDate,
		&i.PrintedDate,
	)
	return i, err
}

const getPrinterConfig = `-- name: GetPrinterConfig :one
SELECT name, ip, updated_at FROM printer_configs WHERE name = $1
`

func (q *Queries) GetPrinterConfig(ctx context.Context, name string) (PrinterConfig, error) {
	row := q.db.QueryRow(ctx, getPrinterConfig, name)
	var i PrinterConfig
	err := row.Scan(&i.Name, &i.Ip, &i.UpdatedAt)
	return i, err
}

const listArrivedOrders = `-- name: ListArrivedOrders :many
SELECT order_id, payload, state, arrival_date, printed_date
FROM orders
WHERE state = 'arrived'
ORDER BY arrival_date ASC
`

// Pending-acceptance queue. Used by mobile to populate the "awaiting you" list
// when it connects or reconnects to the SSE stream.
func (q *Queries) ListArrivedOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listArrivedOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.Payload,
			&i.State,
			&i.ArrivalDate,
			&i.PrintedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersPage = `-- name: ListOrdersPage :many
SELECT order_id, payload, state, arrival_date, printed_date
FROM orders
ORDER BY arrival_date DESC
LIMIT $1 OFFSET $2
`

type ListOrdersPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Newest-first, for mobile history view.
func (q *Queries) ListOrdersPage(ctx context.Context, arg ListOrdersPageParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.Payload,
			&i.State,
			&i.ArrivalDate,
			&i.PrintedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrinterConfigs = `-- name: ListPrinterConfigs :many
SELECT name, ip, updated_at FROM printer_configs ORDER BY name
`

func (q *Queries) ListPrinterConfigs(ctx context.Context) ([]PrinterConfig, error) {
	rows, err := q.db.Query(ctx, listPrinterConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrinterConfig
	for rows.Next() {
		var i PrinterConfig
		if err := rows.Scan(&i.Name, &i.Ip, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccepted = `-- name: MarkAccepted :exec
UPDATE orders
SET state        = 'accepted',
    printed_date = COALESCE(printed_date, now())
WHERE order_id = $1
`

// First-time accept: sets state + printed_date. COALESCE preserves any earlier
// printed_date (so this is safe even if called twice, though the state check
// below ordinarily prevents that).
func (q *Queries) MarkAccepted(ctx context.Context, orderID int32) error {
	_, err := q.db.Exec(ctx, markAccepted, orderID)
	return err
}

const setAutoAccept = `-- name: SetAutoAccept :exec
INSERT INTO settings (id, auto_accept, updated_at)
VALUES (1, $1, now())
ON CONFLICT (id) DO UPDATE SET
    auto_accept = EXCLUDED.auto_accept,
    updated_at  = EXCLUDED.updated_at
`

func (q *Queries) SetAutoAccept(ctx context.Context, autoAccept bool) error {
	_, err := q.db.Exec(ctx, setAutoAccept, autoAccept)
	return err
}

const setPrinterIP = `-- name: SetPrinterIP :exec
INSERT INTO printer_configs (name, ip, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (name) DO UPDATE SET
    ip         = EXCLUDED.ip,
    updated_at = EXCLUDED.updated_at
`

type SetPrinterIPParams struct {
	Name string `json:"name"`
	Ip   string `json:"ip"`
}

// Mobile-update path: always overwrite. updated_at moves so mobile can tell
// how fresh the value is.
func (q *Queries) SetPrinterIP(ctx context.Context, arg SetPrinterIPParams) error {
	_, err := q.db.Exec(ctx, setPrinterIP, arg.Name, arg.Ip)
	return err
}

const upsertArrivedOrder = `-- name: UpsertArrivedOrder :exec
INSERT INTO orders (order_id, payload, state, arrival_date)
VALUES ($1, $2, 'arrived', now())
ON CONFLICT (order_id) DO NOTHING
`

type UpsertArrivedOrderParams struct {
	OrderID int32  `json:"order_id"`
	Payload []byte `json:"payload"`
}

// Inserts a freshly-arrived order. Idempotent against duplicate SSE redelivery —
// if the order_id already exists (e.g. mobile reconnected and main/ resends),
// we leave the existing row (and its state/printed_date) alone.
func (q *Queries) UpsertArrivedOrder(ctx context.Context, arg UpsertArrivedOrderParams) error {
	_, err := q.db.Exec(ctx, upsertArrivedOrder, arg.OrderID, arg.Payload)
	return err
}

const upsertPrinterConfigIfAbsent = `-- name: UpsertPrinterConfigIfAbsent :exec
INSERT INTO printer_configs (name, ip)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
`

type UpsertPrinterConfigIfAbsentParams struct {
	Name string `json:"name"`
	Ip   string `json:"ip"`
}

// Env-var seed path: only populate a row if none exists for this printer.
// Mobile-set values are never overwritten at boot.
func (q *Queries) UpsertPrinterConfigIfAbsent(ctx context.Context, arg UpsertPrinterConfigIfAbsentParams) error {
	_, err := q.db.Exec(ctx, upsertPrinterConfigIfAbsent, arg.Name, arg.Ip)
	return err
}
